# This is a basic workflow that is manually triggered

name: Sync + merge

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    paths-ignore:
      - '.github/workflows/restore-readme.yml'
      - '.github/README.md'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          # This ensures the full history is fetched, 
          # which is often needed for merging/rebasing.
          fetch-depth: 0
          submodules: recursive
    # Runs a single command using the runners shell
    - name: Define user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Fetch + merge
      run: |
        git remote add upstream https://github.com/ValveSoftware/Proton.git
        git fetch upstream bleeding-edge
        git merge upstream/bleeding-edge
    - name: Submodules
      run: |
        git config --file .gitmodules submodule.wine.url https://github.com/ValveSoftware/wine.git
        git config --file .gitmodules submodule.dxvk.url https://github.com/ValveSoftware/dxvk.git
        git config --file .gitmodules submodule.vkd3d-proton.url https://github.com/ValveSoftware/vkd3d-proton.git
        git submodule sync
        git submodule update --init --recursive
        git add wine vkd3d vkd3d-proton dxvk dxvk-nvapi FEX
    - name: Push
      run: |
        git add .
        git commit -m "Resolve submodule conflicts by favoring upstream"
        git push origin [your-branch-name]
